### ISSUE TITLE
adding a default name for emptyCdmReference

### ISSUE THREAD

**Issue by ilovemane** [oxford-pharmacoepi/omock#23]
It seem a bit annoying to type in the name of the mock cdm. Shall we have the default to be emptyCdmReference("mock cdm")? @edward-burn @nmercadeb

**Comment by edward-burn** [comment]
We're reexporting this from omopgenerics so for this you might have to persuade @catalamarti

**Comment by catalamarti** [comment]
maybe we can create emptyMock():
```
emptyMock <- function() {
omopgenerics::emptyCdmReference(cdmName = "mock database")
}
```

So I see why for omock it is nice to have a default, but this deafult does not make sense for omopgenerics.

@edward-burn @ilovemane @nmercadeb

**Comment by ilovemane** [comment]
this sound cool to me!

**Comment by edward-burn** [comment]
mockCdmReference() %>% mockPerson() ?
