### ISSUE TITLE
mockConditionOccurence()

### ISSUE THREAD

**Issue by ilovemane** [oxford-pharmacoepi/omock#51]

**Comment by ilovemane** [comment]
mockConditionOccurence(cdm, nConcept, recordPerson, seed)

This is my suggestion for the condition occurence table.

- nConcept - number of different concept id you want in the table. (It uses the concept_id in the concept table from mockVocabulary, if nConcept > number of unique conditions in the vocabulary it will through an error. 
- recordPerson - the average number of records per person for each concept. Can take a vector; if nConcept = 2, you can do c(0.5,10) etc...

@edward-burn @catalamarti

**Comment by catalamarti** [comment]
`recordPerson = 2.5`

**Comment by catalamarti** [comment]
delete `nConcept` -> we use all present concepts
