### ISSUE TITLE
mockDrugEra()

### ISSUE THREAD

**Issue by ilovemane** [oxford-pharmacoepi/omock#53]

**Comment by ilovemane** [comment]
suggestions? I think there are two ways we can possibly have this. As I guess it can only be generated if drugExposure table exist.

1. mockDrugExposure() |> mockDrugEra()

2. mockDrugExposure(drugEra = T)

I think we need both, as user can give as their own drug_exposure table and we use mockDrugEra() to compute the drugEra table for them using mockDrugEra()?

@edward-burn @catalamarti

**Comment by catalamarti** [comment]
for the moment we do not populate conditionEra or drugEra tables...
Will see in the future...

**Comment by ilovemane** [comment]
I will close this for now.
