### ISSUE TITLE
Proposal: to add mockCdmReferenece as a default for the mock functions

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/omock#54]

**Comment by ilovemane** [comment]
I am happy to add it for persons, observations, cohorts and vocabularies. I am not sure you want it for clinical tables...., just dont make any sense for people to create clinical tables (e.g. condition_occurances, drug exposure) without person, observations and vocabulary tables

**Comment by catalamarti** [comment]
agrred:
- mockPerson
- mockVocabularies
- mockCdmFromTables
