### ISSUE TITLE
FeatureRequest: to add `vocabulary` argument in mockCdmReference()

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/omock#65]
This argument will determine which vocabulary is added, all vocabulary tables will be created, but their content will be different depending on the mode.

My proposed options:
- **minimal**: this would provide a very simple vocabulary with only gender_concept_ids, type concept ids.
- **eunomia**: this would add the eunomia vocabulary tables.
- **default** (*consider to change name*): this would add the tables that mike is working on right now.
- **expanded** (*consider to change name*): this would an expanded version of the tables that mike is working on right now.
- ...

What do you think @edward-burn ?
@ilovemane seemed happy with this option

**Comment by ilovemane** [comment]
mockvocabulary(concept_set = list()), assumpt to be standard, 

concept_id =,
standard = ",
relationships = "random"

take xx concept, make conditions table with the concept.
